services:
  - type: web
    name: fraud-detection-kmeans
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn fraud_detection.wsgi:application --timeout 120 --workers 2 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "fraud-detection-kmeans.onrender.com"
      - key: GUNICORN_CMD_ARGS
        value: "--timeout=120 --workers=2 --threads=2"
    healthCheckPath: /
    autoDeploy: true
    plan: free